In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mphs/.local/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting numpy>=1.20.3 (from pandas)
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)
Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 70.5 MB/s eta 0:00:00
Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 91.7 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
WARNING: Error parsing dependencies of celery: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.24.4 pandas-2.0.3 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [8]:
df = pd.DataFrame()

In [9]:
print(df)

Empty DataFrame
Columns: []
Index: []

In [34]:
df = pd.DataFrame([1,2,3],columns=["a"],index=[1,2,3])
print(df)

   a
1  1
2  2
3  3

In [20]:
df.index

Index([1, 2, 3], dtype='int64')

In [21]:
df.index.to_list()

[1, 2, 3]

In [23]:
df['a']

1    1
2    2
3    3
Name: a, dtype: int64

In [35]:
print(df.loc(0)[3])

a    3
Name: 3, dtype: int64

In [44]:
df = pd.DataFrame([[1,2],[3,4,5],[6,7,8],[9,19]],columns=['c1','c2','c3'],index=['r1','r2','r3', 'r4'])

In [45]:
df

    c1  c2   c3
r1   1   2  NaN
r2   3   4  5.0
r3   6   7  8.0
r4   9  19  NaN

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, r1 to r4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      4 non-null      int64
 1   c2      4 non-null      int64
 2   c3      2 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 128.0+ bytes

In [47]:
df.describe()

         c1         c2       c3
count  4.00   4.000000  2.00000
mean   4.75   8.000000  6.50000
std    3.50   7.615773  2.12132
min    1.00   2.000000  5.00000
25%    2.50   3.500000  5.75000
50%    4.50   5.500000  6.50000
75%    6.75  10.000000  7.25000
max    9.00  19.000000  8.00000

In [48]:
df.isna().sum()

c1    0
c2    0
c3    2
dtype: int64

In [50]:
df = pd.DataFrame([[1,2],[3,4,5],[6,7,8],[9,None,19]],columns=['c1','c2','c3'],index=['r1','r2','r3','r4'])

In [51]:
df

    c1   c2    c3
r1   1  2.0   NaN
r2   3  4.0   5.0
r3   6  7.0   8.0
r4   9  NaN  19.0

In [53]:
df.shape

(4, 3)

In [71]:
df['c2']['r4'] = 9

/tmp/ipykernel_8807/3148638810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['c2']['r4'] = 9

In [72]:
df

    c1   c2    c3
r1   1  2.0   NaN
r2   3  4.0   5.0
r3   6  7.0   8.0
r4   9  9.0  19.0

In [75]:
list(df['c2'])

[2.0, 4.0, 7.0, 9.0]

In [78]:
df['c2'] = [int(i) for i in df['c2']]

In [79]:
df

    c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0

In [83]:
print(df.index)
df.index.to_list()

Index(['r1', 'r2', 'r3', 'r4'], dtype='object')

['r1', 'r2', 'r3', 'r4']

In [86]:
df.nunique

<bound method DataFrame.nunique of     c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0>

In [87]:
df['c2']['r1']

2

In [94]:
df.loc['r1']['c2']

2.0

In [113]:
df1=pd.DataFrame(df,columns=[1,2,3],index=[0,1,3,4])

In [114]:
df1

    1   2   3
0 NaN NaN NaN
1 NaN NaN NaN
3 NaN NaN NaN
4 NaN NaN NaN

In [109]:
df

    c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0

In [122]:
a=[1,2,3,4]
b=['add','sub','mul','div']

df1 = pd.DataFrame(a,b)

In [123]:
df1

     0
add  1
sub  2
mul  3
div  4

In [124]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, add to div
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      int64
dtypes: int64(1)
memory usage: 64.0+ bytes

In [130]:
df1 = pd.DataFrame([{1,2,3,4},{3,4,5,6}])

In [131]:
df1

   0  1  2  3
0  1  2  3  4
1  3  4  5  6

In [148]:

df1 = pd.DataFrame({"a":[1,1,3,2],"b":[1,3,2,4]})

In [149]:
df1

   a  b
0  1  1
1  1  3
2  3  2
3  2  4

In [150]:
df1.nunique()

a    3
b    4
dtype: int64

In [151]:
df1["a"].unique()

array([1, 3, 2])

In [152]:
df

    c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0

In [157]:
df[df['c3'].isna()]

    c1  c2  c3
r1   1   2 NaN

In [162]:
df[df['c3']==5]

    c1  c2   c3
r2   3   4  5.0

In [163]:
df1 = pd.read_csv('./nba.csv')

In [165]:
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [166]:
df1.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [169]:
df1.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [173]:
df1.loc[1,"Team"] = "Boston Celtics"

In [174]:
df1.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [183]:
df1.sort_values(["Name","Team"],ascending=[1,1])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
...,...,...,...,...,...,...,...,...,...
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [182]:
type(df1.loc[1,"Height"])

str

In [190]:
len(df1["Name"].unique())

458

In [195]:
df1["College"].isna().sum()

85

In [194]:
len(df1["Salary"].unique())

310

In [200]:
df1.query("Age < 25 and College == 'Florida'")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
88,Marreese Speights,Golden State Warriors,5.0,C,28.0,6-10,255.0,Florida,3815000.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
232,David Lee,Dallas Mavericks,42.0,PF,33.0,6-9,245.0,Florida,2085671.0
238,Chandler Parsons,Dallas Mavericks,25.0,SF,27.0,6-10,230.0,Florida,15361500.0
245,Corey Brewer,Houston Rockets,33.0,SG,30.0,6-9,186.0,Florida,8229375.0
296,Matt Bonner,San Antonio Spurs,15.0,C,36.0,6-10,235.0,Florida,947276.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
343,Udonis Haslem,Miami Heat,40.0,PF,36.0,6-8,235.0,Florida,2854940.0
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674.0
392,Mike Miller,Denver Nuggets,3.0,SG,36.0,6-8,218.0,Florida,947276.0

In [201]:
df1.query("Age > 25 and College == 'Duke'")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
42,Lance Thomas,New York Knicks,42.0,SF,28.0,6-8,235.0,Duke,1636842.0
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
103,JJ Redick,Los Angeles Clippers,4.0,SG,31.0,6-4,190.0,Duke,7085000.0
154,Mike Dunleavy,Chicago Bulls,34.0,SG,35.0,6-9,230.0,Duke,4500000.0
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
224,Miles Plumlee,Milwaukee Bucks,18.0,C,27.0,6-11,249.0,Duke,2109294.0
340,Luol Deng,Miami Heat,9.0,SF,31.0,6-9,220.0,Duke,10151612.0
346,Josh McRoberts,Miami Heat,4.0,PF,29.0,6-10,240.0,Duke,5543725.0
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,28.0,6-8,228.0,Duke,4500000.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0

In [202]:
df

    c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0

In [205]:
df.where(df['c3']>10,inplace=True)

In [206]:
df

     c1   c2    c3
r1  NaN  NaN   NaN
r2  NaN  NaN   NaN
r3  NaN  NaN   NaN
r4  9.0  9.0  19.0

In [211]:
df['c1'] = [1,3,6,9]

In [212]:
df

    c1   c2    c3
r1   1  NaN   NaN
r2   3  NaN   NaN
r3   6  NaN   NaN
r4   9  9.0  19.0

In [213]:
df['c2'] = [2,4,7,9]

In [214]:
df['c3'] = [None,5,8,19]

In [215]:
df

    c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0

In [218]:
df['c2'].where(df['c1']>5, other=1)

r1    1
r2    1
r3    7
r4    9
Name: c2, dtype: int64

In [219]:
df

    c1  c2    c3
r1   1   2   NaN
r2   3   4   5.0
r3   6   7   8.0
r4   9   9  19.0

In [224]:

df.insert(3,'c4',[True,False,False,True])

In [225]:
df

    c1  c2    c3     c4
r1   1   2   NaN   True
r2   3   4   5.0  False
r3   6   7   8.0  False
r4   9   9  19.0   True

In [227]:
df['c3']['r1']

nan

In [231]:
df1.iloc[6:10:2,:2]

            Name            Team
6  Jordan Mickey  Boston Celtics
8   Terry Rozier  Boston Celtics

In [234]:
df1.loc[:,['Team']].head()

             Team
0  Boston Celtics
1  Boston Celtics
2  Boston Celtics
3  Boston Celtics
4  Boston Celtics

In [235]:
df1 = pd.DataFrame({
    "A" : ["A1", "A2"],
    "B" : ["B1", "B2"]
})

In [253]:
df2 = pd.DataFrame({
    "A" : ["A3", "A4"],
    "B" : ["B3", "B4"]
},index=[3,4])

In [240]:
df = pd.concat([df1,df2],ignore_index=True)

In [241]:
df

    A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [242]:
df3 = pd.DataFrame({
    "C":["C2","C3","C4","C5"],
    "D":["D2","D3","D4","D5"]
},index=[2,3,4,5])

In [243]:
df3

    C   D
2  C2  D2
3  C3  D3
4  C4  D4
5  C5  D5

In [263]:
df = pd.concat([pd.concat([df1,df2],axis=0,ignore_index=True),df3],axis=1)

In [264]:
df

     A    B    C    D
0   A1   B1  NaN  NaN
1   A2   B2  NaN  NaN
2   A3   B3   C2   D2
3   A4   B4   C3   D3
4  NaN  NaN   C4   D4
5  NaN  NaN   C5   D5

In [266]:
dt1 = pd.DataFrame({
    "key" : ["a","b","c"],
    "name": ["A","B","C"]
})

dt2 = pd.DataFrame({
    "key" : ["a","b","c"],
    "place" : ["AP","TPG","WG"]
})

In [267]:
dt = pd.merge(dt1,dt2,on="key")

In [268]:
dt

  key name place
0   a    A    AP
1   b    B   TPG
2   c    C    WG